# Generated by Django 3.1.3 on 2020-12-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('global_file', models.FileField(upload_to='media', verbose_name='Selecione')),
                ('individual_file', models.CharField(max_length=50, verbose_name='Indivudual')),
            ],
            options={
                'verbose_name': 'Upload CSV',
                'verbose_name_plural': 'Upload CSV',
            },
        ),
    ]
