# Generated by Django 3.1.3 on 2021-04-07 11:20

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadcsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadCSV',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
